name: Deploy Dumi to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --registry=https://registry.npmmirror.com/


      - name: Update .dumirc.ts for GitHub Pages
        run: |
          # 动态修改 base 和 publicPath
          sed -i 's|base: .*|base: "/lucky-design/",|' .dumirc.ts
          sed -i 's|publicPath: .*|publicPath: "/lucky-design/",|' .dumirc.ts
          echo "Updated .dumirc.ts successfully."

      - name: Build project
        run: pnpm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs-dist
